import { Component, Input } from '@angular/core';
import { EventItem } from 'src/app/models/event-item.model';

/**
 * Displays the events generated by the application.
 */
@Component({
  selector: 'event-list',
  templateUrl: './event-list.component.html'
})
export class EventListComponent {

  /**
   * The last date and time when the displayed data was refreshed.
   */
  @Input() public lastUpdate: Date = new Date();

  /**
   * The list of events to be displayed.
   */
  @Input() public eventList: EventItem[] = [];

}